# Generated by Django 4.1.2 on 2022-10-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('UMUM', 'Umum'), ('LELANG', 'Lelang'), ('GALANG', 'Galang Dana')], max_length=6)),
                ('teks_pertanyaan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_user.generaluser')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('pertanyaan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_service.pertanyaan')),
            ],
        ),
    ]
