# Generated by Django 4.1.2 on 2022-10-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertanyaan',
            name='user',
        ),
    ]
