# Generated by Django 4.1.2 on 2022-10-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0005_alter_faq_pertanyaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='jawaban',
            field=models.TextField(max_length=500),
        ),
    ]
