# Generated by Django 4.1.2 on 2022-10-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_alter_faq_jawaban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='jawaban',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='kategori',
            field=models.CharField(choices=[('UMUM', 'Umum'), ('LELANG', 'Lelang'), ('GALANG', 'Galang Dana')], default='UMUM', max_length=6),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='teks_pertanyaan',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='pertanyaan',
            unique_together={('kategori', 'teks_pertanyaan')},
        ),
    ]
