# Generated by Django 4.1.2 on 2022-10-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0007_alter_faq_jawaban_alter_pertanyaan_kategori_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pertanyaan',
            unique_together=set(),
        ),
    ]
