# Generated by Django 4.1.2 on 2022-10-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_user', '0001_initial'),
        ('testimoni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonilist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_user.generaluser'),
        ),
    ]
