# Generated by Django 4.1.2 on 2022-11-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0006_remove_testimonilist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonilist',
            name='nama',
            field=models.CharField(blank=True, default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonilist',
            name='target',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
    ]
