# Generated by Django 4.1.2 on 2022-11-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0007_alter_testimonilist_nama_alter_testimonilist_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonilist',
            name='title',
        ),
    ]
