# Generated by Django 4.1.2 on 2022-11-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_user', '0001_initial'),
        ('testimoni', '0008_remove_testimonilist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonilist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_user.generaluser'),
        ),
    ]
