# Generated by Django 4.1.2 on 2022-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_user", "0001_initial"),
        ("resipien", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Komentar", new_name="KomentarGalangDana",),
        migrations.AlterField(
            model_name="galangdana",
            name="gambar",
            field=models.ImageField(blank=True, upload_to="resipien/"),
        ),
    ]
