# Generated by Django 4.1.2 on 2022-10-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resipien", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="galangdana", name="akun_bank",),
    ]
