# Generated by Django 4.1.2 on 2022-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resipien", "0002_remove_galangdana_akun_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galangdana",
            name="gambar",
            field=models.ImageField(blank=True, upload_to="resipien/upload"),
        ),
    ]
