# Generated by Django 4.1.2 on 2022-10-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("general_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarangLelang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_barang", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("gambar", models.ImageField(upload_to="")),
                ("starting_bid", models.PositiveIntegerField()),
                ("tanggal_mulai", models.DateField(auto_now_add=True)),
                ("tanggal_berakhir", models.DateField()),
                ("status_keaktifan", models.BooleanField(default=True)),
                (
                    "kategori_barang",
                    models.CharField(
                        choices=[
                            ("ANTIK", "Barang Antik"),
                            ("PERHIASAN", "Perhiasan"),
                            ("TEKNOLOGI", "Teknologi"),
                            ("FIGURAN", "Figuran"),
                            ("OTHER", "Lainnya"),
                        ],
                        default="ANTIK",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banyak_bid", models.PositiveIntegerField()),
                (
                    "barang_lelang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="lelang.baranglelang",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general_user.generaluser",
                    ),
                ),
            ],
        ),
    ]
