# Generated by Django 4.1.2 on 2022-10-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resipien", "0001_initial"),
        ("lelang", "0001_initial"),
        ("general_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baranglelang",
            name="galang_dana_tujuan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="resipien.galangdana"
            ),
        ),
        migrations.AddField(
            model_name="baranglelang",
            name="pelelang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_user.generaluser",
            ),
        ),
    ]
