# Generated by Django 4.1.2 on 2022-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lelang", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baranglelang",
            name="gambar",
            field=models.ImageField(upload_to="lelang/upload"),
        ),
    ]
