# Generated by Django 4.1.2 on 2022-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lelang", "0008_alter_baranglelang_gambar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baranglelang",
            name="tanggal_berakhir",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="baranglelang",
            name="tanggal_mulai",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
