# Generated by Django 4.1.2 on 2022-10-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lelang", "0011_baranglelang_bid_tertinggi"),
    ]

    operations = [
        migrations.RemoveField(model_name="baranglelang", name="bid_tertinggi",),
    ]
