# Generated by Django 4.1.2 on 2022-10-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lelang", "0013_baranglelang_bid_tertinggi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baranglelang",
            name="gambar",
            field=models.ImageField(
                default="lelang/product-image-placeholder.jpg", upload_to="lelang/"
            ),
        ),
    ]
